# Generated by Django 2.2.1 on 2019-09-20 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dailyexpense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exview',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dailyexpense.Expense')),
            ],
            bases=(django.views.generic.list.ListView, 'dailyexpense.expense'),
        ),
    ]
