# Generated by Django 2.2.1 on 2019-09-21 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposit', '0002_auto_20190919_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='depoview',
            fields=[
                ('deposit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deposit.Deposit')),
            ],
            bases=(django.views.generic.list.ListView, 'deposit.deposit'),
        ),
    ]
